spring:
  transaction:
    rollback-on-commit-failure: true
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    druid:
      master:
        url: jdbc:mysql://rm-2zewb8ua94pdgftgno.mysql.rds.aliyuncs.com:3306/budianpay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
        username: budianpay_dev
        password: budianpay001%$#@!
        initial-size: 2
      slave:
        url: jdbc:mysql://rm-2zewb8ua94pdgftgno.mysql.rds.aliyuncs.com:3306/budianpay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
        username: budianpay_dev
        password: budianpay001%$#@!
        initial-size: 4
  dubbo:
      application:
        name: provider
      registry:
        address: zookeeper://169.254.48.184:2181
      protocol:
        name: dubbo
        host: 169.254.48.184
        port: 20880
      scan: com.meetcity.payment.core
  redis:
    host: 192.168.209.132
    password:
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    #配置上传文件限制大小
  http:
    multipart:
      max-file-size: 15Mb  #单个文件大小
      max-request-size: 15Mb  #总上传的数据大小


mapper:
  not-empty: false
  identity: MYSQL
#配置pageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    root: info
    com.meetcity: debug
    #配置端口号
server:
  port: 8080
  context-path: /brcd
  #配置mybatis扫描
mybatis:
  #Mapper.xml所在的位置
  mapper-locations:  classpath:mapper/*Mapper.xml
  config-location: classpath:mapper/config/sqlMapConfig.xml
  #entity扫描的包名
  type-aliases-package: com.meetcity.payment.model
#图片服务器配置
 #ftp:
   #ftp_address: 169.254.105.60
  # ftp_port: 21
  # ftp_username: ftpuser
  # ftp_password: ftpuser
   #ftp_base_path: D:\\apps\\img
 #  image_base_url: http://169.254.105.60
  # imagepath: /
#微信扫码支付
#brcd:
   #测试商户
 #  mch_id: C149628461779610201
   #商户秘钥
 #  key: acc503c56b0c4fd399f7f7093d25223c
   #请求网关
 #  gateway.url: http://www.brcb-sandbox.sunfund.com/gateway
   #进件接口
 #   customer.report.url: http://www.brcb-sandbox.sunfund.com/customer/service
   #后台回掉地址
 #  notify.url: http://localhost:8080/brcd/wechatNotify
   #前台结果地址
 #  callback.url: http://localhost:8080/brcd/wechatNotify
   #本地访问
#domain.name: http://localhost:8080
#支付宝扫码支付
   #支付宝网关
#   alipay.url: https://openapi.alipaydev.com/gateway.do
   #支付宝APP_ID
#   alipay.app_id: 2016081900287198
   #应用私钥
#   alipay.app_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCWxA1oz/oBUCQU38PwW83ixb+dVOHCC848wHdzJ2CpMd57J8CAYuZh6XSO42MeYEwKe4xHYJyT2C69pxeQ91ekeTFhKjL4WYllZgzDJSJ0jq+QKZliBp+fVaugXHSGQu8YYTHA44/cnC3/JuWhwzZMlZwqVa+7eGgtNIJWkX7XVuA6/yl4y27E4Y6O+H8IchIuez0XtHejQu+IFvWew2A7szeVFCglIv8dOOhD7ay7ydte+gcjm7WmTqXvVFuJMVSpNqwome7FfXJnFtYdNmMM9O0JO9ga6KSufjA5bHCSyIJ1ZP3KpeKBTAVN5k0vOQ7E/0iGaIiMpz3WLtD04JCbAgMBAAECggEBAIesvKiC6Of/l8jVKf4Gj7ww2uQZ++PlPd58EcKmQB1izGUl+91NoyefsI3Z4Vv3qtaQIkglkCKYHE/9q36Ap/VSPvbCxAWshbGjaX6/z0b3FNT2KpsFfOYlcYKpUQ918raM2PpNjywnvFjuRx4Qj6/Rvyx12eQqUg3EQDrpSi08EkstTsx846ScTZOb996VRhrLq5tNfMT6xiGfQBy5BG7ujJ58DMr+T4yWEWElGoOzKNkmqv7Knpp91yGccGnk799xP2AXWSZGbNmZGaRvbQ0d6TMB7G/cnzyZvGgFzbepfflV4TcJfaweO49HzPFFQOvclQ3gbH8RSEto+0BMGlECgYEA5WJsnY3pRzs/BTxd6nza6BjDELvPQF6N6NWhbSRKdYePNGsgkDq2pBZGJa5GhOXZvH9ZHTKmhUjqUC3PrX1AgbGSQj0Sm+M3pVVFMEFqFf872M5GPgubAYMk4ZlnzLIrlM6bUlK11U2FiQcfqK0L0Oep1Hq5nLI/k5ujFC/iEqMCgYEAqEJcW5AzCtf2bqL2+C3B6sRhZ+DgOmeYWebbq5yor215fI4XpDriyvpacin533x18PTfuiPFeXltKmHHIrAU8r1Md9bPz970MiEM8vs7oOZrFrfGZAPUouP74xg14/y1k4XBgKpcOg97vYyf4SFL3UINegH61FQyUiG2LpXL4akCgYEA4XJnBkMf796PBfpa48hq7orHzX6JJ97G4vx0d+yfMfxWB1Ly4k6Si5tIvmgW7y9pXRZc45GQkJcllEAySXU9HTsFYQzdaVFcs6anJdJlDdGZZHD4IKsPYeEfMouvtUO4Cb02cybPiCF1CURzHTlWz6+g/zDPlO6sBcuF8KVPMLkCgYBLg8T5nyUZV8WU7/TRe4/NcqeYvHdGHxpkNtUeFygp24MroIYBwh/pIyUWmbo4UB6Krwv9+XH2S8XvwIRkEAzGyKiaHEGWNKT6HpU2NAUV+HPVdVNHreRv2sxApqwBD3japawrt8m+kRZjAsr6ejwXKD7uJBdT1hnjfJfMHpSrSQKBgEyfF3cQDzhmRC3l7GvIaRpcTuYCBcUwuTw8nZF/nqYRRVhgXxns+URAeB+vmgXY/DR8YRMKn7fDFdTsg/fMrpJEOo8+27Ju/0JX1MJPf3fbzqToRrZSLZK5M6EP6eX2DqW3O0fi/VzcPm1DRHrpuKioQoOy6wMtBF91hq2UZGzb
   #参数返回格式,只支持json
#   alipay.format: json
   #请求和签名使用字符编码格式,支持GBK和UTF-8
#   alipay.charset: UTF-8
   #支付宝公钥,由支付宝生成
#   alipay.alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt9Kt/oCDt63OJBm1tE3fVdjZjmbfqi45bpkF5TZDzl0tFItArjIsOm96A0U6vkxxwKNsRaqif9XEkAeLmIECLa7HaowUVn9l6B3otfMVhqr0KVrmRcBELBScZQexd5+Q+vCiQ35dnc41Oy4jZJ780BXOLVl0dzTI4YDicO3CTaqeqgytyOn3BupLyyQ1SuPFo9agve2DIl175bOFnWFO9pfg7zEOaK+6asngf8yXBr/5xGHjwLJZ1Yen/Wk6XYRNKb4dKfhXu+zN+2k5j/Bo3BQoOfNxFQyHp4gZnf9sBDxqVuJLRIaZ5j8gJxk6i3UcXdKk2Uyr9hr2GRvBrUbksQIDAQAB
   #商户生成签名字符串所使用的签名算法类型，目前支持RSA2和RSA，推荐使用RSA2
 #  alipay.sign_type: RSA2
   #支付宝回掉地址